name: Run Line Item Monitoring

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install googleads gspread oauth2client

      - name: Check credentials file
        run: |
          echo "Contents of GOOGLE_APPLICATION_CREDENTIALS:"
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > credentials.json
          cat credentials.json  # Print the contents (not recommended for production)

      - name: Check googleads.yaml file
        run: |
          echo "Contents of GOOGLE_APPLICATION_GOOGLEADS:"
          echo "${{ secrets.GOOGLE_APPLICATION_GOOGLEADS }}" | base64 --decode > googleads.yaml
          cat googleads.yaml  # Print the contents (not recommended for production)

      - name: Run the script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_GOOGLEADS: ${{ secrets.GOOGLE_APPLICATION_GOOGLEADS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python githubmain.py  # Replace with the actual name of your script
