name: Run Line Item Monitoring

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # This adds a manual trigger option

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          pip install googleads gspread oauth2client

      - name: Print credentials.json
        run: |
          echo "Contents of credentials.json:"
          cat path/to/your/credentials.json  # Update with the actual path

      - name: Print googleads.yaml
        run: |
          echo "Contents of googleads.yaml:"
          cat path/to/your/googleads.yaml  # Update with the actual path

      - name: Run the script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_GOOGLEADS: ${{ secrets.GOOGLE_APPLICATION_GOOGLEADS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python githubmain.py  # Ensure this matches the actual name of your script
