name: Scheduled Python Script 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # This runs the job every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with all dependencies

      - name: Create credentials file
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json" >> $GITHUB_ENV

      - name: Set other environment variables
        run: |
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          
          # Decode GOOGLE_APPLICATION_GOOGLEADS if it's Base64 encoded
          echo "${{ secrets.GOOGLE_APPLICATION_GOOGLEADS }}" | base64 --decode > $HOME/google_ads_config.json
          echo "GOOGLE_APPLICATION_GOOGLEADS=$HOME/google_ads_config.json" >> $GITHUB_ENV

      - name: Run the Python script
        run: python githubmain.py
