name: Run Line Item Monitoring

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          pip install googleads gspread oauth2client

      - name: Decode credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

      - name: Run the script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json  # Path to the decoded credentials
          GOOGLE_APPLICATION_GOOGLEADS: ${{ secrets.GOOGLE_APPLICATION_GOOGLEADS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python githubmain.py  # Ensure this matches the actual name of your script
