name: Scheduled Python Script 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # This runs the job every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the Python version you need

      # Step 3: Install dependencies using pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with all dependencies

      # Step 4: Set GOOGLE_APPLICATION_CREDENTIALS from GitHub Secrets
      - name: Create GOOGLE_APPLICATION_CREDENTIALS file
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json  # Set it explicitly in the env block

      # Step 5: Create googleads.yaml from a base64-encoded secret
      - name: Create googleads.yaml file
        run: |
          echo "${{ secrets.GOOGLEADS_CONFIG }}" | base64 --decode > $HOME/googleads.yaml
        env:
          GOOGLEADS_CONFIG: $HOME/googleads.yaml  # Set this in the env block

      # Step 6: Set EMAIL_PASSWORD from GitHub Secrets
      - name: Set EMAIL_PASSWORD
        run: echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      # Step 7: Run the Python script
      - name: Run the Python script
        run: python githubmain.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json  # Make sure to pass this to the script
          GOOGLEADS_CONFIG: $HOME/googleads.yaml  # Ensure googleads.yaml is set in the environment
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # Pass email password secret to the script
