name: Run Script Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # This sets the schedule to run every 15 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Make sure you have a requirements.txt file with your dependencies

      - name: Create credentials file from secrets
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > temp_credentials.json
          echo "${{ secrets.EMAIL_PASSWORD }}" > email_password.txt

      - name: Run the script
        run: python githubmain.py
